---

- name: Create /home/ubuntu/bin
  file: path=/home/ubuntu/bin state=directory

- name: Download repo
  get_url:
    url: https://storage.googleapis.com/git-repo-downloads/repo
    dest: /home/ubuntu/bin/repo
    mode: u=rx,g=rx,o=rx
    checksum: sha256:0cf5f52bcafb8e1d3ba0271b087312f6117b824af272bedd4ee969d52363a86b

- name: Create source directory
  file: path={{ source_dir }} state=directory

# The option --depth=1 ensures a shallow clone which takes less time to download.
- name: Run repo init
  command: ~/bin/repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b {{ source_tag }}
  args:
    chdir: "{{ source_dir }}"

# The option -c limits downloads to the current branch.
- name: Run repo sync
  command: ~/bin/repo sync -c -j16
  args:
    chdir: "{{ source_dir }}"